openapi: 3.0.0
info:
  version: 1.0.0
  title: Customers API
  description: A simple API to get customer data

servers:
  - url: https://customers.api.k8.local

paths:
  /customers/{customer_id}:
    get:
      description: Returns a customer 
      parameters:
      - name: customer_id
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: Successfully returns a customer
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
        400:
          $ref: '#/components/responses/400Error'
  /customers:
    post:
      description: Lets a user post a new artist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          description: Successfully created a new artist
        '400':
          $ref: '#/components/responses/400Error'  
      x-kong-plugin-key-auth:
        name: key-auth
        enabled: true
        config:
          key_names: [api_key, apikey]
          key_in_body: false
          hide_credentials: true
      x-kong-plugin-request-validator:
        enabled: true
        
components:
  schemas:
    Customer:
      type: object
      required:
        - customers_requested
      properties:
        customers_id:
          type: string

  responses:
    400Error:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object 
            properties:
              message:
                type: string
