openapi: 3.0.0
info:
  version: 1.0.0
  title: Products API
  description: A simple API to get product data

servers:
  - url: http://product-api.apps.svc.cluster.local:8080

paths:
  /products/{product_id}:
    get:
      description: Returns a product 
      parameters:
      - name: product_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Successfully returns a product
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '400':
          $ref: '#/components/responses/400Error'
  /products:
    post:
      description: Lets a user post a new artist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Successfully created a new artist
        '400':
          $ref: '#/components/responses/400Error'  
      x-kong-plugin-key-auth:
        name: key-auth
        enabled: true
        config:
          key_names: [api_key, apikey]
          key_in_body: false
          hide_credentials: true
      x-kong-plugin-request-validator:
        enabled: true
        
components:
  schemas:
    Product:
      type: object
      required:
        - products_requested
      properties:
        products_id:
          type: string

  responses:
    400Error:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object 
            properties:
              message:
                type: string
