openapi: 3.0.0
info:
  version: 1.0.0
  title: Customers API v1
  description: A simple API to get customer data

servers:
  - url: http://customer-api-v1.apps.svc.cluster.local:8080
  - url: http://customer-api-v1-5.apps.svc.cluster.local:8080

paths:
  /v1/customers/{customer_id}:
    get:
      description: Returns a customer 
      parameters:
      - name: customer_id
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: Successfully returns a customer
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
        400:
          $ref: '#/components/responses/400Error'
  /v1/customers:
    post:
      description: Lets a user post a new artist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          description: Successfully created a new artist
        '400':
          $ref: '#/components/responses/400Error'  
        
components:
  schemas:
    Customer:
      type: object
      required:
        - customers_requested
      properties:
        customers_id:
          type: string

  responses:
    400Error:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object 
            properties:
              message:
                type: string
